In [1]:
import torch 
import torch.nn as nn 

class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.up = nn.Linear(2,5) 
        self.act = nn.GELU()
        self.down = nn.Linear(5,2)
    
    def forward(self, x):
        x = self.up(x)
        x = self.act(x)
        x = self.down(x)
        return x
    
model = Model()


In [2]:
model.eval()
input = torch.tensor([[1,2]]).float()
output = model.forward(input)
print(output)

# ---- modify module output
def backward_hook(module, grad_inputs, grad_outputs):
    #modify gradient signals 
    print("I'm backward hook")
    print(grad_inputs)
    return grad_inputs

hook = model.act.register_full_backward_hook(backward_hook)
output = model.forward(input)
output.sum().backward()
hook.remove()
print(output)

tensor([[-0.0038, -0.1055]], grad_fn=<AddmmBackward0>)
I'm backward hook
(tensor([[ 0.0782,  0.0049,  0.6948, -0.0778, -0.0017]]),)
tensor([[-0.0038, -0.1055]], grad_fn=<AddmmBackward0>)
