In [2]:
import torch 
import torch.nn as nn 

class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.up = nn.Linear(2,5) 
        self.act = nn.GELU()
        self.down = nn.Linear(5,2)
    
    def forward(self, x):
        x = self.up(x)
        x = self.act(x)
        x = self.down(x)
        return x

In [3]:
model = Model()

# ---- modify module output
model.eval()
input = torch.tensor([[1,2]]).float()
output = model.forward(input)
print(output)

# ---- modify module output
def hook_fn(module, input, output):
    return output * 10000

hook = model.act.register_forward_hook(hook_fn)
output = model.forward(input)
hook.remove()
print(output)

# ---- check original output
output = model.forward(input)
print(output)

tensor([[-0.7901,  0.0772]], grad_fn=<AddmmBackward0>)
tensor([[-4291.5962,  5209.7759]], grad_fn=<AddmmBackward0>)
tensor([[-0.7901,  0.0772]], grad_fn=<AddmmBackward0>)
